name: spm-build-docs

on:
  push:
    branches: [ "docs" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docs
      run: swift package generate-documentation --target SwiftCloudant
    - name: Unpack Docs
      run: mv ./.build/plugins/Swift-DocC/outputs/SwiftCloudant.doccarchive ./docs